### ISSUE TITLE
allow non-global install

### ISSUE THREAD

**Issue by nherment** [apparatus/fuge#45]
It's a bad practice to clutter your global PATH with project dependent tools.

Most 'global' NPM modules, including fuge, are targeted at building and maintaining projects.

I always install these into the local node_modules of the project and add node_modules/.bin to the $PATH so that I can use another version of the 'global' tool for another project.

For some reason, Fuge can't work like that:

```
➜  fubar git:(master) ✗ export $PATH=PATH:node_modules/.bin
➜  fubar git:(master) ✗ npm i fuge
...
➜  fubar git:(master) ✗ fuge generate system
module.js:341
    throw err;
    ^

Error: Cannot find module '/home/nherment/workspace/nearform/fubar/node_modules/fuge/node_modules/generator-fuge/generators/app/index.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.require.resolve (internal/module.js:23:19)
    at locateGenerator (/home/nherment/workspace/nearform/fubar/node_modules/fuge/util.js:85:20)
    at /home/nherment/workspace/nearform/fubar/node_modules/fuge/generator.js:72:20
    at Array.forEach (native)
    at createEnv (/home/nherment/workspace/nearform/fubar/node_modules/fuge/generator.js:71:16)
    at Object.generateSystem (/home/nherment/workspace/nearform/fubar/node_modules/fuge/generator.js:426:11)
    at Command.generateSystem [as func] (/home/nherment/workspace/nearform/fubar/node_modules/fuge/fuge.js:43:15)
    at Command.call (/home/nherment/workspace/nearform/fubar/node_modules/commist/index.js:100:8)
    at Object.parse (/home/nherment/workspace/nearform/fubar/node_modules/commist/index.js:58:19)
```

**Comment by AdrianRossouw** [comment]
I agree, and it's probably a one line fix in utils.js somewhere.

The way it tries to find generators, and frankly [most things around scaffolding in general](https://github.com/apparatus/fuge/issues/25) needs work.

**Comment by tswaters** [comment]
I've found another bug with using fuge as a local project dependency.  Not sure if it's the same one line fix, but here's the report... this doesn't at all relate to the generators, and is running under Windows, if that makes any difference.

When run as a local dependency the resolution to any `env_file` files in `system.yml` will be relative to fuge directory.  When run as a global dependency, the resolution will be to the root of the project (or maybe cwd, unsure)

I had a heck of a time figuring out why I could `npm start` my project fine with an npm script that ran `fuge build` and `fuge run` but failed when I typed `fuge shell` manually from the command line, invoking the global bin command.

Also, maybe a separate bug - but if it fails to load the env file, no errors are reported.  When using `fuge run` will will just not show anything.  Inside `fuge shell` you can at least use `info $app` and it will report:

```
Error: D:\Code\system.env does not exist
not managed or unknown process
```

... that is when the project is located in D:\code\fuge-tests

**Comment by mcdonnelldean** [comment]
It wasn't build with this in mind so I think trying to bash it in will end in trouble. For now this isn't officially supported.
